version: "3"
services:
  mysql:
    build: 
      context: .
      dockerfile: ./mysql/Dockerfile
      args:
        - "http_proxy"
        - "https_proxy"
    ports:
      - "3306:3306"
    container_name: "mysql"
    volumes:
      - "./mysql/init:/docker-entrypoint-initdb.d"
      - "./mysql/data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: secret
  adminer:
    image: adminer:latest
    container_name: "adminer"
    restart: always
    ports:
      - "8080:8080"
  nodeapp:
    ports:
      - "3000:3000"
    volumes:
      - "./app:/mnt"
    container_name: "nodeapp"
    build: 
      context: .
      dockerfile: ./nodeapp/Dockerfile
      args:
        - "http_proxy"
        - "https_proxy"
    env_file: .env
  nodeapi:
    ports:
      - "4000:3000"
    volumes:
      - "./api:/mnt"
    container_name: "nodeapi"
    build: 
      context: .
      dockerfile: ./nodeapp/Dockerfile
      args:
        - "http_proxy"
        - "https_proxy"
    command: /sbin/init -D
    env_file: .env
